# Generated by Django 5.0.1 on 2024-01-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.CharField(max_length=20),
        ),
    ]
